# -*- coding: utf-8 -*-
"""498(IR).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnHKHezHD5vreGafx62a-3MM-ckmqhCg
"""

!unzip -qq /content/phishing-sites-screenshot.zip -d dataset

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2
from tensorflow.keras.models import Model
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

img_size = 224
batch_size = 16
dataset_path = "dataset"

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True
)

train_gen = train_datagen.flow_from_directory(
    dataset_path,
    subset="training",
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode="binary"
)

val_gen = train_datagen.flow_from_directory(
    dataset_path,
    subset="validation",
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode="binary"
)

base_model = MobileNetV2(
    input_shape=(img_size, img_size, 3),
    include_top=False,
    weights="imagenet"
)

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
preds = Dense(1, activation="sigmoid")(x)

model = Model(inputs=base_model.input, outputs=preds)

for layer in base_model.layers:
    layer.trainable = False

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10,
    verbose=1
)

val_gen.reset()
preds = model.predict(val_gen)
pred_labels = (preds > 0.5).astype(int)

true_labels = val_gen.classes
class_indices = val_gen.class_indices
labels_map = {v:k for k,v in class_indices.items()}

print("\nClassification Report:\n")
print(classification_report(true_labels, pred_labels, target_names=labels_map.values()))

cm = confusion_matrix(true_labels, pred_labels)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=labels_map.values(),
            yticklabels=labels_map.values())
plt.title("Confusion Matrix")
plt.show()

model.save("phishing_cnn_model.h5")
print("Saved as phishing_cnn_model.h5")